# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1
_src_path: /Users/samvaughan/Code/spv-copier-template
copyright_date: '2023'
email: sam.vaughan@mq.edu.au
github_repo_name: magpi-stellar-pops
name: Sam Vaughan
project_description: Measuring stellar populations for the MAGPI galaxy survey
project_name: MAGPI stellar populations
